spring.application.name=hospitalSystem

spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=Sangam4251

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql

jwt.secretKey=ioaure9q090934ru09yh899898f0q49u3rjq0w93ur02002ruq0020h88fhh9qief9340