# ==========================================
# Application
# ==========================================
spring.application.name=hospitalSystem
server.servlet.context-path=/api


# ==========================================
# Database
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=Sangam4251


# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false


# ==========================================
# Database Initialization
# ==========================================
spring.sql.init.mode=never


# ==========================================
# JWT
# ==========================================
jwt.secretKey=akjfcincnvniwe994939tu349394vn438v893v48n484c4tu848tc487nnm@3n84n9n4cnr0c0